// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkflowEngineV1._0.Data;

#nullable disable

namespace WorkflowEngineV1._0.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240724113033_addEntitiesToDb")]
    partial class addEntitiesToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkflowEngineV1._0.Models.Connection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EndTaskId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "endTaskId");

                    b.Property<string>("StartTaskId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "startTaskId");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("int");

                    b.Property<float>("XLoc")
                        .HasColumnType("real")
                        .HasAnnotation("Relational:JsonPropertyName", "xLoc");

                    b.Property<float>("YLoc")
                        .HasColumnType("real")
                        .HasAnnotation("Relational:JsonPropertyName", "yLoc");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId");

                    b.ToTable("Connections");

                    b.HasAnnotation("Relational:JsonPropertyName", "connections");
                });

            modelBuilder.Entity("WorkflowEngineV1._0.Models.TaskItem", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<int?>("WorkflowId")
                        .HasColumnType("int");

                    b.Property<int>("X")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "x");

                    b.Property<int>("Y")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "y");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId");

                    b.ToTable("TaskItems");

                    b.HasAnnotation("Relational:JsonPropertyName", "tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Task 1",
                            X = 100,
                            Y = 100
                        },
                        new
                        {
                            Id = 2,
                            Name = "Task 2",
                            X = 300,
                            Y = 100
                        },
                        new
                        {
                            Id = 3,
                            Name = "Task 3",
                            X = 100,
                            Y = 300
                        },
                        new
                        {
                            Id = 4,
                            Name = "Task 4",
                            X = 300,
                            Y = 300
                        },
                        new
                        {
                            Id = 5,
                            Name = "Task 5",
                            X = 200,
                            Y = 500
                        });
                });

            modelBuilder.Entity("WorkflowEngineV1._0.Models.Workflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("WorkflowName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "workflowName");

                    b.HasKey("Id");

                    b.ToTable("Workflows");
                });

            modelBuilder.Entity("WorkflowEngineV1._0.Models.Connection", b =>
                {
                    b.HasOne("WorkflowEngineV1._0.Models.Workflow", "Workflow")
                        .WithMany("Connections")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("WorkflowEngineV1._0.Models.TaskItem", b =>
                {
                    b.HasOne("WorkflowEngineV1._0.Models.Workflow", "Workflow")
                        .WithMany("Tasks")
                        .HasForeignKey("WorkflowId");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("WorkflowEngineV1._0.Models.Workflow", b =>
                {
                    b.Navigation("Connections");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
